apiVersion: v1
kind: Service
metadata:
  name: otoorders
  labels:
    run: otoorders
spec:
  ports:
    # the port that this service should serve on
    - port: 8080 
      targetPort: 8080
  type: LoadBalancer
  loadBalancerSourceRanges:
  - 0.0.0.0/0
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: otoorders
spec:
  replicas: 2
  template:
    metadata:
      labels:
        run: otoorders
    spec:
      containers:
      - name: otoorders
        image: antweiss/otoorders:master
        ports:
        - containerPort: 8080
