apiVersion: v1
kind: Service
metadata:
  name: orders
  labels:
    run: orders
spec:
  ports:
    # the port that this service should serve on
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
      run: orders
  type: LoadBalancer
  loadBalancerSourceRanges:
  - 0.0.0.0/0
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: orders
spec:
  replicas: 2
  template:
    metadata:
      labels:
        run: orders
    spec:
      containers:
      - name: orders
        image: ynigmatulin/oto-orders:BUILD_NUMBER
        ports:
        - containerPort: 8080
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
